#!/bin/bash
echo "========================================="
echo "CipherPay UI Log Checking Guide"
echo "========================================="
echo ""
echo "1. BROWSER CONSOLE (Main):"
echo "   - Press F12 in your browser"
echo "   - Go to 'Console' tab"
echo "   - Look for [AuthService] and [CipherPayService] logs"
echo ""
echo "2. TERMINAL LOGS:"
echo "   - Check the terminal where you ran 'npm start'"
echo "   - Shows compilation/build errors"
echo ""
echo "3. NETWORK TAB:"
echo "   - Press F12 → 'Network' tab"
echo "   - Filter by 'Fetch/XHR'"
echo "   - Look for requests to http://localhost:8788"
echo ""
echo "Current running processes:"
ps aux | grep -E "react-scripts|npm.*start" | grep -v grep || echo "No React dev server found running"
echo ""
echo "========================================="
